#!/usr/bin/env python3

import json
from pathlib import Path

from openai import OpenAI


REPORTS = [
    "archive-summary.json",
    "core-comparison.json",
    "archive-flags.tsv",
    "root-php-files.txt",
]


def load_reports(report_dir):
    sections = []

    for name in REPORTS:
        path = report_dir / name

        if not path.exists():
            continue

        sections.append(
            f"\n===== {name} =====\n"
            + path.read_text(encoding="utf-8", errors="replace")
        )

    return "\n".join(sections)


def main():
    report_dir = Path("/root/forensics/reports")

    evidence = load_reports(report_dir)

    client = OpenAI()

    instructions = """
You are performing initial forensic triage of a WordPress multisite
filesystem.

The supplied reports were generated by deterministic, read-only tools.
No files have been executed.

Your task is to:

1. Decide whether the evidence supports possible compromise.
2. Identify and prioritize the findings that deserve further investigation.
3. Explain why each finding matters.
4. State exactly what additional evidence or file contents you would
   request next.
5. Distinguish clearly between:
   - established facts,
   - reasonable hypotheses,
   - unknowns.
6. Do not classify a file as malicious merely because it is absent from
   the official WordPress distribution.
7. Treat expected site-specific files such as wp-config.php and .htaccess
   as potentially security-sensitive rather than automatically safe.
8. Do not propose executing any PHP or other files.

Return your assessment as JSON with these top-level keys:

overall_assessment
facts
priority_findings
requested_evidence
hypotheses
unknowns
"""

    response = client.responses.create(
        model="gpt-5.6-luna",
        instructions=instructions,
        input=evidence,
    )

    output = response.output_text

    output_path = report_dir / "ai-triage.txt"
    output_path.write_text(output, encoding="utf-8")

    print(output)
    print(f"\nSaved to: {output_path}")


if __name__ == "__main__":
    main()
